"""
netcheck.report
===============
Output renderers: Markdown report, JSON document, and JSON-lines audit log.
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone

from .core import worst_severity, VERDICT_BY_SEVERITY, SEVERITY


def verdict(results) -> str:
    return VERDICT_BY_SEVERITY[worst_severity(results)]


def build_document(env, results, findings, ai_result=None, mode="triage") -> dict:
    return {
        "tool": "NetCheck",
        "schema": "netcheck-report-2",
        "mode": mode,
        "verdict": verdict(results),
        "environment": env,
        "checks": [r.to_dict() for r in results],
        "findings": findings,
        "ai_analysis": ai_result,
    }


def write_json(path, env, results, findings, ai_result=None, mode="triage"):
    doc = build_document(env, results, findings, ai_result, mode)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, indent=2, default=str)
    return path


def write_markdown(path, env, results, findings, ai_result=None, mode="triage"):
    v = verdict(results)
    L = []
    L.append(f"# NetCheck Report ({mode})\n")
    L.append(f"**Verdict:** `{v}`  ")
    L.append(f"**Generated:** {env.get('timestamp')}  ")
    if env.get("operator"):
        L.append(f"**Operator:** {env['operator']}  ")
    L.append(f"**Host:** {env.get('hostname')}  ·  **OS:** {env.get('os')}  ·  "
             f"**Target:** {env.get('target')}\n")

    L.append("## Environment\n")
    L.append("| Field | Value |")
    L.append("|---|---|")
    L.append(f"| Local IPv4 | {env.get('local_ip') or '—'} |")
    L.append(f"| Local IPv6 | {env.get('local_ipv6') or '—'} |")
    L.append(f"| Gateway | {env.get('gateway') or '—'} |")
    L.append(f"| Configured DNS | {', '.join(env.get('dns_servers') or []) or '—'} |")
    L.append("")

    # Group checks by category
    cats = {}
    for r in results:
        cats.setdefault(r.category, []).append(r)
    titles = {"diagnostic": "Diagnostic Results",
              "security": "Security Posture",
              "forensic": "Forensic Collection"}
    for cat, rows in cats.items():
        L.append(f"## {titles.get(cat, cat.title())}\n")
        L.append("| Status | Check | Detail | Time |")
        L.append("|---|---|---|---|")
        for r in rows:
            detail = (r.detail or "").replace("|", "\\|")
            L.append(f"| `{r.status}` | {r.name} | {detail} | {r.duration_ms:.0f}ms |")
        L.append("")
        if cat == "security":
            refs = []
            for r in rows:
                ref = (r.data or {}).get("nist")
                if ref and ref not in refs:
                    refs.append(ref)
            if refs:
                L.append("**NIST mapping:** " + "; ".join(refs) + "\n")

    L.append("## Diagnosis (rule-based)\n")
    if not findings:
        L.append("_No findings._\n")
    for i, f in enumerate(findings, 1):
        L.append(f"### {i}. [{f['severity']}] {f['title']}\n")
        L.append(f"- **Why:** {f['cause']}")
        L.append(f"- **Fix:** {f['fix']}\n")

    if ai_result and ai_result.get("ok"):
        L.append("## AI Analysis\n")
        L.append(f"_Provider: {ai_result.get('provider')} · model: {ai_result.get('model')}_\n")
        L.append(ai_result.get("text", "").strip() + "\n")
    elif ai_result and ai_result.get("error"):
        L.append("## AI Analysis\n")
        L.append(f"_AI analysis unavailable: {ai_result['error']}_\n")

    L.append("---")
    L.append("_Generated by NetCheck_")

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    return path


def append_audit_log(path, env, results, findings, mode="triage"):
    """Append one JSON object per run - a tamper-resistant audit trail / SIEM feed."""
    record = {
        "ts": datetime.now(timezone.utc).isoformat(),
        "mode": mode,
        "operator": env.get("operator"),
        "host": env.get("hostname"),
        "target": env.get("target"),
        "verdict": verdict(results),
        "summary": {r.name: r.status for r in results},
        "top_finding": findings[0] if findings else None,
    }
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "a", encoding="utf-8") as fh:
        fh.write(json.dumps(record, default=str) + "\n")
    return record
